In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## 讀取資料

In [2]:
raw_df = pd.read_csv('svc50.csv')
raw_df.head(5)

id  height  weight  bmi-gt class-gt  CJWR   WHR   PAR     ES   FWR  \
0  290248.jpg    1.75   72.57   23.70        b  1.21  1.77  0.02  42.50  1.25   
1  290250.jpg    1.88   94.35   26.69        c  1.23  1.65  0.02  43.57  1.27   
2  290391.jpg    1.80   90.72   28.00        c  1.19  1.64  0.02  38.53  1.31   
3  290418.jpg    1.73   74.84   25.01        c  1.25  1.50  0.02  40.01  1.29   
4  291245.jpg    1.96   92.99   24.21        b  1.22  1.55  0.02  37.61  1.18   

     MEH    CFR  
0  29.00  36.90  
1  25.27  39.63  
2  24.98  41.28  
3  42.41  39.41  
4  27.14  36.37

In [3]:
raw_data = list(raw_df.values)

## 抽取 test-data，並製作 test-df

In [4]:
test_size = 0.2
test_count = int(len(raw_df) * test_size)
pick_index = list(np.random.choice(len(raw_df), test_count, replace=False))

In [5]:
test_data = list()
for i in pick_index:
    test_data.append(raw_data.pop(i))

In [6]:
test_df = pd.DataFrame(columns=raw_df.columns)
for d in test_data:
    test_df.loc[len(test_df)] = d
    
test_df

id  height  weight  bmi-gt class-gt  CJWR   WHR   PAR     ES   FWR  \
0  293900.jpg    1.70   84.37   29.19        c  1.19  1.80  0.02  42.57  1.31   
1  295669.jpg    1.55   56.70   23.60        b  1.24  1.65  0.02  47.51  1.37   
2  295004.jpg    1.85   74.84   21.87        b  1.23  1.68  0.02  41.05  1.20   
3  295118.jpg    1.65   62.14   22.82        b  1.24  1.66  0.02  44.57  1.23   
4  293599.jpg    1.78  104.33   32.93        d  1.17  1.76  0.02  40.00  1.39   
5  290250.jpg    1.88   94.35   26.69        c  1.23  1.65  0.02  43.57  1.27   
6  295540.jpg    1.75   74.84   24.44        b  1.22  1.65  0.03  31.62  1.44   
7  295866.jpg    1.80   90.72   28.00        c  1.24  1.80  0.03  32.51  1.38   
8  290418.jpg    1.73   74.84   25.01        c  1.25  1.50  0.02  40.01  1.29   
9  292839.jpg    1.65   75.75   27.82        c  1.17  1.64  0.02  39.51  1.28   

     MEH    CFR  
0  30.31  40.58  
1  36.54  40.25  
2  29.01  30.61  
3  43.82  32.29  
4  30.97  45.10  
5  25.27  39.63  
6  25.27  45.94  
7  23.36  37.69  
8  42.41  39.41  
9  27.93  42.68

## 製作 train-df

In [7]:
train_df = pd.DataFrame(columns=raw_df.columns)
for d in raw_data:
    train_df.loc[len(train_df)] = d

train_df

id  height  weight  bmi-gt class-gt  CJWR   WHR   PAR     ES  \
0   290248.jpg    1.75   72.57   23.70        b  1.21  1.77  0.02  42.50   
1   290391.jpg    1.80   90.72   28.00        c  1.19  1.64  0.02  38.53   
2   291245.jpg    1.96   92.99   24.21        b  1.22  1.55  0.02  37.61   
3   291424.jpg    1.85   83.91   24.52        b  1.21  1.52  0.02  37.51   
4   291870.jpg    1.78   81.65   25.77        c  1.17  1.70  0.03  31.53   
5   291920.jpg    1.75   80.74   26.36        c  1.24  1.52  0.02  43.57   
6   291955.jpg    1.75   79.38   25.92        c  1.24  1.51  0.02  42.50   
7   292132.jpg    1.73   73.48   24.55        b  1.23  1.81  0.02  44.01   
8   292209.jpg    1.68   68.04   24.11        b  1.26  1.65  0.02  41.05   
9   292527.jpg    1.83   90.72   27.09        c  1.19  1.48  0.02  38.01   
10  293091.jpg    1.80   81.65   25.20        c  1.19  1.43  0.03  32.51   
11  293101.jpg    1.73   72.57   24.25        b  1.18  1.73  0.03  31.00   
12  293250.jpg    1.68   58.97   20.89        b  1.25  1.62  0.02  38.51   
13  293273.jpg    1.80   83.91   25.90        c  1.19  1.72  0.02  35.03   
14  293439.jpg    1.80   77.11   23.80        b  1.25  1.56  0.02  41.08   
15  293826.jpg    1.78   81.65   25.77        c  1.23  1.46  0.02  45.50   
16  293851.jpg    1.88   90.72   25.67        c  1.22  1.57  0.03  34.50   
17  293964.jpg    1.52   63.50   27.48        c  1.26  1.81  0.02  37.62   
18  294211.jpg    1.73   87.09   29.10        c  1.20  1.56  0.02  40.57   
19  294278.jpg    1.75   84.37   27.55        c  1.11  1.65  0.02  31.50   
20  294466.jpg    1.70   63.50   21.97        b  1.26  1.88  0.02  45.00   
21  294516.jpg    1.75   65.77   21.48        b  1.24  1.42  0.03  30.99   
22  294668.jpg    1.57   68.04   27.60        c  1.29  1.65  0.02  43.07   
23  294770.jpg    1.68   58.97   20.89        b  1.18  1.73  0.02  39.53   
24  294831.jpg    1.78   88.45   27.92        c  1.20  1.72  0.02  48.09   
25  295012.jpg    1.78   68.04   21.47        b  1.16  1.68  0.02  39.70   
26  295016.jpg    1.83   90.72   27.09        c  1.14  1.65  0.02  49.61   
27  295026.jpg    1.75   58.97   19.26        b  1.21  1.64  0.03  30.59   
28  295087.jpg    1.83  113.40   33.86        d  1.17  1.82  0.02  37.00   
29  295212.jpg    1.65   58.97   21.66        b  1.15  1.72  0.02  34.56   
30  295563.jpg    1.50   45.36   20.16        b  1.18  1.51  0.02  39.50   
31  295624.jpg    1.63   70.31   26.46        c  1.16  1.70  0.02  42.67   
32  295634.jpg    1.70   74.84   25.90        c  1.24  1.64  0.02  40.15   
33  295700.jpg    1.60   63.50   24.80        b  1.26  1.45  0.02  36.62   
34  295712.jpg    1.75   53.07   17.33        a  1.19  1.69  0.03  33.03   
35  295741.jpg    1.78   68.04   21.47        b  1.19  1.62  0.03  34.00   
36  295868.jpg    1.78   95.25   30.06        d  1.15  1.50  0.02  38.03   
37  295871.jpg    1.65   54.43   19.99        b  1.19  1.59  0.02  48.00   
38  295926.jpg    1.75   90.72   29.62        c  1.22  1.71  0.05  19.52   
39  295977.jpg    1.63   63.50   23.90        b  1.17  1.74  0.02  40.55   

     FWR    MEH    CFR  
0   1.25  29.00  36.90  
1   1.31  24.98  41.28  
2   1.18  27.14  36.37  
3   1.18  24.35  39.76  
4   1.45  22.23  42.11  
5   1.19  35.33  37.13  
6   1.20  32.28  39.23  
7   1.33  28.56  35.93  
8   1.28  30.91  33.18  
9   1.25  28.72  44.62  
10  1.26  17.85  45.92  
11  1.35  24.06  40.00  
12  1.37  29.30  39.14  
13  1.42  24.87  43.67  
14  1.32  34.82  40.95  
15  1.30  31.83  42.73  
16  1.48  22.85  43.77  
17  1.42  28.70  35.69  
18  1.45  34.00  44.10  
19  1.23  27.49  45.22  
20  1.41  28.75  36.63  
21  1.29  26.95  48.92  
22  1.34  36.96  39.68  
23  1.63  31.40  48.67  
24  1.26  35.41  36.47  
25  1.25  21.37  44.18  
26  1.18  35.88  42.35  
27  1.34  23.55  45.74  
28  1.36  21.81  42.39  
29  1.36  29.81  44.51  
30  1.27  32.38  39.53  
31  1.47  31.13  46.81  
32  1.34  39.27  41.00  
33  1.32  29.39  39.31  
34  1.18  22.24  35.

In [8]:
x_train = train_df.iloc[:,5:len(train_df.columns)].values
x_train

array([[1.210e+00, 1.770e+00, 2.000e-02, 4.250e+01, 1.250e+00, 2.900e+01,
        3.690e+01],
       [1.190e+00, 1.640e+00, 2.000e-02, 3.853e+01, 1.310e+00, 2.498e+01,
        4.128e+01],
       [1.220e+00, 1.550e+00, 2.000e-02, 3.761e+01, 1.180e+00, 2.714e+01,
        3.637e+01],
       [1.210e+00, 1.520e+00, 2.000e-02, 3.751e+01, 1.180e+00, 2.435e+01,
        3.976e+01],
       [1.170e+00, 1.700e+00, 3.000e-02, 3.153e+01, 1.450e+00, 2.223e+01,
        4.211e+01],
       [1.240e+00, 1.520e+00, 2.000e-02, 4.357e+01, 1.190e+00, 3.533e+01,
        3.713e+01],
       [1.240e+00, 1.510e+00, 2.000e-02, 4.250e+01, 1.200e+00, 3.228e+01,
        3.923e+01],
       [1.230e+00, 1.810e+00, 2.000e-02, 4.401e+01, 1.330e+00, 2.856e+01,
        3.593e+01],
       [1.260e+00, 1.650e+00, 2.000e-02, 4.105e+01, 1.280e+00, 3.091e+01,
        3.318e+01],
       [1.190e+00, 1.480e+00, 2.000e-02, 3.801e+01, 1.250e+00, 2.872e+01,
        4.462e+01],
       [1.190e+00, 1.430e+00, 3.000e-02, 3.251e+01, 1.260e+0

In [9]:
y_train = train_df.iloc[:,4:5].values
y_train = np.hstack(y_train)
y_train

array(['b', 'c', 'b', 'b', 'c', 'c', 'c', 'b', 'b', 'c', 'c', 'b', 'b',
       'c', 'b', 'c', 'c', 'c', 'c', 'c', 'b', 'b', 'c', 'b', 'c', 'b',
       'c', 'b', 'd', 'b', 'b', 'c', 'c', 'b', 'a', 'b', 'd', 'b', 'c',
       'b'], dtype=object)

In [10]:
x_test = test_df.iloc[:,5:len(train_df.columns)].values
x_test

array([[1.190e+00, 1.800e+00, 2.000e-02, 4.257e+01, 1.310e+00, 3.031e+01,
        4.058e+01],
       [1.240e+00, 1.650e+00, 2.000e-02, 4.751e+01, 1.370e+00, 3.654e+01,
        4.025e+01],
       [1.230e+00, 1.680e+00, 2.000e-02, 4.105e+01, 1.200e+00, 2.901e+01,
        3.061e+01],
       [1.240e+00, 1.660e+00, 2.000e-02, 4.457e+01, 1.230e+00, 4.382e+01,
        3.229e+01],
       [1.170e+00, 1.760e+00, 2.000e-02, 4.000e+01, 1.390e+00, 3.097e+01,
        4.510e+01],
       [1.230e+00, 1.650e+00, 2.000e-02, 4.357e+01, 1.270e+00, 2.527e+01,
        3.963e+01],
       [1.220e+00, 1.650e+00, 3.000e-02, 3.162e+01, 1.440e+00, 2.527e+01,
        4.594e+01],
       [1.240e+00, 1.800e+00, 3.000e-02, 3.251e+01, 1.380e+00, 2.336e+01,
        3.769e+01],
       [1.250e+00, 1.500e+00, 2.000e-02, 4.001e+01, 1.290e+00, 4.241e+01,
        3.941e+01],
       [1.170e+00, 1.640e+00, 2.000e-02, 3.951e+01, 1.280e+00, 2.793e+01,
        4.268e+01]])

In [12]:
y_test = test_df.iloc[:,4:5].values
y_test = np.hstack(y_test)
y_test

array(['c', 'b', 'b', 'b', 'd', 'c', 'b', 'c', 'c', 'c'], dtype=object)

## SVC

In [13]:
from sklearn.svm import SVC

In [14]:
clf = SVC()

In [15]:
len(x_train), type(x_train), x_train.shape

(40, numpy.ndarray, (40, 7))

In [16]:
clf.fit(x_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [17]:
y_test_predict = clf.predict(x_test)

In [20]:
y_test_predict

array(['b', 'b', 'b', 'b', 'b', 'b', 'b', 'b', 'b', 'b'], dtype=object)

In [21]:
y_test

array(['c', 'b', 'b', 'b', 'd', 'c', 'b', 'c', 'c', 'c'], dtype=object)

In [22]:
x_train

array([[1.210e+00, 1.770e+00, 2.000e-02, 4.250e+01, 1.250e+00, 2.900e+01,
        3.690e+01],
       [1.190e+00, 1.640e+00, 2.000e-02, 3.853e+01, 1.310e+00, 2.498e+01,
        4.128e+01],
       [1.220e+00, 1.550e+00, 2.000e-02, 3.761e+01, 1.180e+00, 2.714e+01,
        3.637e+01],
       [1.210e+00, 1.520e+00, 2.000e-02, 3.751e+01, 1.180e+00, 2.435e+01,
        3.976e+01],
       [1.170e+00, 1.700e+00, 3.000e-02, 3.153e+01, 1.450e+00, 2.223e+01,
        4.211e+01],
       [1.240e+00, 1.520e+00, 2.000e-02, 4.357e+01, 1.190e+00, 3.533e+01,
        3.713e+01],
       [1.240e+00, 1.510e+00, 2.000e-02, 4.250e+01, 1.200e+00, 3.228e+01,
        3.923e+01],
       [1.230e+00, 1.810e+00, 2.000e-02, 4.401e+01, 1.330e+00, 2.856e+01,
        3.593e+01],
       [1.260e+00, 1.650e+00, 2.000e-02, 4.105e+01, 1.280e+00, 3.091e+01,
        3.318e+01],
       [1.190e+00, 1.480e+00, 2.000e-02, 3.801e+01, 1.250e+00, 2.872e+01,
        4.462e+01],
       [1.190e+00, 1.430e+00, 3.000e-02, 3.251e+01, 1.260e+0